added final step for reference in PRs

diff --git a/.github/workflows/tests_diff.yml b/.github/workflows/tests_diff.yml
--- a/.github/workflows/tests_diff.yml
+++ b/.github/workflows/tests_diff.yml
@@ -206,3 +206,21 @@ jobs:
               --dockerfile ./tests/Dockerfile_standalone \
               --docker-build-args "--build-arg PYTHON_VERSION=3.12" \
               --docker-run-args "$ENV_VARS"
+
+
+  final:
+    name: Runnability of changed examples
+    runs-on: ubuntu-latest
+    needs:
+      - test_peripheral
+      - test_standalone
+    if: always()
+    steps:
+      - name: Fail if any previous job failed
+        if: ${{ needs.test_peripheral.result == 'failure' || needs.test_standalone.result == 'failure' || needs.test_peripheral.result == 'cancelled' || needs.test_standalone.result == 'cancelled' }}
+        run: |
+          echo "❌ One or more required tests failed or were cancelled."
+          exit 1
+
+      - name: All required jobs passed
+        run: echo "✅ All tests passed successfully."
